/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as vendorLayoutRouteImport } from './routes/(vendor)/_layout'
import { Route as storeLayoutRouteImport } from './routes/(store)/_layout'
import { Route as authVendorSignUpRouteImport } from './routes/(auth)/vendor-sign-up'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as adminForbiddenRouteImport } from './routes/(admin)/forbidden'
import { Route as adminAdminRouteImport } from './routes/(admin)/admin'
import { Route as storeLayoutIndexRouteImport } from './routes/(store)/_layout/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as vendorShopSlugRouteImport } from './routes/(vendor)/shop/$slug'
import { Route as vendorLayoutMyShopRouteImport } from './routes/(vendor)/_layout/my-shop'
import { Route as vendorLayoutDashboardRouteImport } from './routes/(vendor)/_layout/dashboard'
import { Route as storeLayoutWishlistRouteImport } from './routes/(store)/_layout/wishlist'
import { Route as storeLayoutTrackOrderRouteImport } from './routes/(store)/_layout/track-order'
import { Route as storeLayoutProfileRouteImport } from './routes/(store)/_layout/profile'
import { Route as storeLayoutOrdersRouteImport } from './routes/(store)/_layout/orders'
import { Route as storeLayoutOrderConfirmationRouteImport } from './routes/(store)/_layout/order-confirmation'
import { Route as storeLayoutCheckoutRouteImport } from './routes/(store)/_layout/checkout'
import { Route as storeLayoutCartRouteImport } from './routes/(store)/_layout/cart'
import { Route as adminAdminUsersRouteImport } from './routes/(admin)/admin/users'
import { Route as adminAdminTransactionsRouteImport } from './routes/(admin)/admin/transactions'
import { Route as adminAdminTaxesRouteImport } from './routes/(admin)/admin/taxes'
import { Route as adminAdminTagsRouteImport } from './routes/(admin)/admin/tags'
import { Route as adminAdminStaffRouteImport } from './routes/(admin)/admin/staff'
import { Route as adminAdminSettingsRouteImport } from './routes/(admin)/admin/settings'
import { Route as adminAdminReviewsRouteImport } from './routes/(admin)/admin/reviews'
import { Route as adminAdminProductsRouteImport } from './routes/(admin)/admin/products'
import { Route as adminAdminMyStoreRouteImport } from './routes/(admin)/admin/my-store'
import { Route as adminAdminCouponsRouteImport } from './routes/(admin)/admin/coupons'
import { Route as adminAdminCategoriesRouteImport } from './routes/(admin)/admin/categories'
import { Route as adminAdminBrandsRouteImport } from './routes/(admin)/admin/brands'
import { Route as adminAdminAttributesRouteImport } from './routes/(admin)/admin/attributes'
import { Route as vendorShopSlugIndexRouteImport } from './routes/(vendor)/shop/$slug/index'
import { Route as storeLayoutStoreIndexRouteImport } from './routes/(store)/_layout/store/index'
import { Route as storeLayoutProductIndexRouteImport } from './routes/(store)/_layout/product/index'
import { Route as storeLayoutCategoryIndexRouteImport } from './routes/(store)/_layout/category/index'
import { Route as adminAdminTenantsIndexRouteImport } from './routes/(admin)/admin/tenants/index'
import { Route as adminAdminOrdersIndexRouteImport } from './routes/(admin)/admin/orders/index'
import { Route as vendorShopSlugTransactionsRouteImport } from './routes/(vendor)/shop/$slug/transactions'
import { Route as vendorShopSlugTaxesRouteImport } from './routes/(vendor)/shop/$slug/taxes'
import { Route as vendorShopSlugTagsRouteImport } from './routes/(vendor)/shop/$slug/tags'
import { Route as vendorShopSlugStaffRouteImport } from './routes/(vendor)/shop/$slug/staff'
import { Route as vendorShopSlugShippingRouteImport } from './routes/(vendor)/shop/$slug/shipping'
import { Route as vendorShopSlugSettingsRouteImport } from './routes/(vendor)/shop/$slug/settings'
import { Route as vendorShopSlugReviewsRouteImport } from './routes/(vendor)/shop/$slug/reviews'
import { Route as vendorShopSlugCouponsRouteImport } from './routes/(vendor)/shop/$slug/coupons'
import { Route as vendorShopSlugCategoriesRouteImport } from './routes/(vendor)/shop/$slug/categories'
import { Route as vendorShopSlugBrandsRouteImport } from './routes/(vendor)/shop/$slug/brands'
import { Route as vendorShopSlugAttributesRouteImport } from './routes/(vendor)/shop/$slug/attributes'
import { Route as storeLayoutStoreSlugRouteImport } from './routes/(store)/_layout/store/$slug'
import { Route as storeLayoutProductProductIdRouteImport } from './routes/(store)/_layout/product/$productId'
import { Route as storeLayoutCategorySlugRouteImport } from './routes/(store)/_layout/category/$slug'
import { Route as adminAdminTenantsTenantIdRouteImport } from './routes/(admin)/admin/tenants/$tenantId'
import { Route as adminAdminOrdersOrderIdRouteImport } from './routes/(admin)/admin/orders/$orderId'
import { Route as vendorShopSlugProductsIndexRouteImport } from './routes/(vendor)/shop/$slug/products/index'
import { Route as vendorShopSlugOrdersIndexRouteImport } from './routes/(vendor)/shop/$slug/orders/index'
import { Route as vendorShopSlugOrdersOrderIdRouteImport } from './routes/(vendor)/shop/$slug/orders/$orderId'

const vendorLayoutRoute = vendorLayoutRouteImport.update({
  id: '/(vendor)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authVendorSignUpRoute = authVendorSignUpRouteImport.update({
  id: '/(auth)/vendor-sign-up',
  path: '/vendor-sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const adminForbiddenRoute = adminForbiddenRouteImport.update({
  id: '/(admin)/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRoute = adminAdminRouteImport.update({
  id: '/(admin)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutIndexRoute = storeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminRoute,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const vendorShopSlugRoute = vendorShopSlugRouteImport.update({
  id: '/(vendor)/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const vendorLayoutMyShopRoute = vendorLayoutMyShopRouteImport.update({
  id: '/my-shop',
  path: '/my-shop',
  getParentRoute: () => vendorLayoutRoute,
} as any)
const vendorLayoutDashboardRoute = vendorLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => vendorLayoutRoute,
} as any)
const storeLayoutWishlistRoute = storeLayoutWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutTrackOrderRoute = storeLayoutTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProfileRoute = storeLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutOrdersRoute = storeLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutOrderConfirmationRoute =
  storeLayoutOrderConfirmationRouteImport.update({
    id: '/order-confirmation',
    path: '/order-confirmation',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutCheckoutRoute = storeLayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCartRoute = storeLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const adminAdminUsersRoute = adminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminTransactionsRoute = adminAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminTaxesRoute = adminAdminTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminTagsRoute = adminAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminStaffRoute = adminAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminSettingsRoute = adminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminReviewsRoute = adminAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminProductsRoute = adminAdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminMyStoreRoute = adminAdminMyStoreRouteImport.update({
  id: '/my-store',
  path: '/my-store',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminCouponsRoute = adminAdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminCategoriesRoute = adminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminBrandsRoute = adminAdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminAttributesRoute = adminAdminAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => adminAdminRoute,
} as any)
const vendorShopSlugIndexRoute = vendorShopSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const storeLayoutStoreIndexRoute = storeLayoutStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductIndexRoute = storeLayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCategoryIndexRoute =
  storeLayoutCategoryIndexRouteImport.update({
    id: '/category/',
    path: '/category/',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const adminAdminTenantsIndexRoute = adminAdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => adminAdminRoute,
} as any)
const adminAdminOrdersIndexRoute = adminAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => adminAdminRoute,
} as any)
const vendorShopSlugTransactionsRoute =
  vendorShopSlugTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)
const vendorShopSlugTaxesRoute = vendorShopSlugTaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugTagsRoute = vendorShopSlugTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugStaffRoute = vendorShopSlugStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugShippingRoute = vendorShopSlugShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugSettingsRoute = vendorShopSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugReviewsRoute = vendorShopSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugCouponsRoute = vendorShopSlugCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugCategoriesRoute =
  vendorShopSlugCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)
const vendorShopSlugBrandsRoute = vendorShopSlugBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => vendorShopSlugRoute,
} as any)
const vendorShopSlugAttributesRoute =
  vendorShopSlugAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)
const storeLayoutStoreSlugRoute = storeLayoutStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutProductProductIdRoute =
  storeLayoutProductProductIdRouteImport.update({
    id: '/product/$productId',
    path: '/product/$productId',
    getParentRoute: () => storeLayoutRoute,
  } as any)
const storeLayoutCategorySlugRoute = storeLayoutCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => storeLayoutRoute,
} as any)
const adminAdminTenantsTenantIdRoute =
  adminAdminTenantsTenantIdRouteImport.update({
    id: '/tenants/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => adminAdminRoute,
  } as any)
const adminAdminOrdersOrderIdRoute = adminAdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => adminAdminRoute,
} as any)
const vendorShopSlugProductsIndexRoute =
  vendorShopSlugProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)
const vendorShopSlugOrdersIndexRoute =
  vendorShopSlugOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)
const vendorShopSlugOrdersOrderIdRoute =
  vendorShopSlugOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => vendorShopSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof adminAdminRouteWithChildren
  '/forbidden': typeof adminForbiddenRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/vendor-sign-up': typeof authVendorSignUpRoute
  '/admin/attributes': typeof adminAdminAttributesRoute
  '/admin/brands': typeof adminAdminBrandsRoute
  '/admin/categories': typeof adminAdminCategoriesRoute
  '/admin/coupons': typeof adminAdminCouponsRoute
  '/admin/my-store': typeof adminAdminMyStoreRoute
  '/admin/products': typeof adminAdminProductsRoute
  '/admin/reviews': typeof adminAdminReviewsRoute
  '/admin/settings': typeof adminAdminSettingsRoute
  '/admin/staff': typeof adminAdminStaffRoute
  '/admin/tags': typeof adminAdminTagsRoute
  '/admin/taxes': typeof adminAdminTaxesRoute
  '/admin/transactions': typeof adminAdminTransactionsRoute
  '/admin/users': typeof adminAdminUsersRoute
  '/cart': typeof storeLayoutCartRoute
  '/checkout': typeof storeLayoutCheckoutRoute
  '/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/orders': typeof storeLayoutOrdersRoute
  '/profile': typeof storeLayoutProfileRoute
  '/track-order': typeof storeLayoutTrackOrderRoute
  '/wishlist': typeof storeLayoutWishlistRoute
  '/dashboard': typeof vendorLayoutDashboardRoute
  '/my-shop': typeof vendorLayoutMyShopRoute
  '/shop/$slug': typeof vendorShopSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin/': typeof adminAdminIndexRoute
  '/': typeof storeLayoutIndexRoute
  '/admin/orders/$orderId': typeof adminAdminOrdersOrderIdRoute
  '/admin/tenants/$tenantId': typeof adminAdminTenantsTenantIdRoute
  '/category/$slug': typeof storeLayoutCategorySlugRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/store/$slug': typeof storeLayoutStoreSlugRoute
  '/shop/$slug/attributes': typeof vendorShopSlugAttributesRoute
  '/shop/$slug/brands': typeof vendorShopSlugBrandsRoute
  '/shop/$slug/categories': typeof vendorShopSlugCategoriesRoute
  '/shop/$slug/coupons': typeof vendorShopSlugCouponsRoute
  '/shop/$slug/reviews': typeof vendorShopSlugReviewsRoute
  '/shop/$slug/settings': typeof vendorShopSlugSettingsRoute
  '/shop/$slug/shipping': typeof vendorShopSlugShippingRoute
  '/shop/$slug/staff': typeof vendorShopSlugStaffRoute
  '/shop/$slug/tags': typeof vendorShopSlugTagsRoute
  '/shop/$slug/taxes': typeof vendorShopSlugTaxesRoute
  '/shop/$slug/transactions': typeof vendorShopSlugTransactionsRoute
  '/admin/orders/': typeof adminAdminOrdersIndexRoute
  '/admin/tenants/': typeof adminAdminTenantsIndexRoute
  '/category/': typeof storeLayoutCategoryIndexRoute
  '/product/': typeof storeLayoutProductIndexRoute
  '/store/': typeof storeLayoutStoreIndexRoute
  '/shop/$slug/': typeof vendorShopSlugIndexRoute
  '/shop/$slug/orders/$orderId': typeof vendorShopSlugOrdersOrderIdRoute
  '/shop/$slug/orders/': typeof vendorShopSlugOrdersIndexRoute
  '/shop/$slug/products/': typeof vendorShopSlugProductsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof adminForbiddenRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/vendor-sign-up': typeof authVendorSignUpRoute
  '/admin/attributes': typeof adminAdminAttributesRoute
  '/admin/brands': typeof adminAdminBrandsRoute
  '/admin/categories': typeof adminAdminCategoriesRoute
  '/admin/coupons': typeof adminAdminCouponsRoute
  '/admin/my-store': typeof adminAdminMyStoreRoute
  '/admin/products': typeof adminAdminProductsRoute
  '/admin/reviews': typeof adminAdminReviewsRoute
  '/admin/settings': typeof adminAdminSettingsRoute
  '/admin/staff': typeof adminAdminStaffRoute
  '/admin/tags': typeof adminAdminTagsRoute
  '/admin/taxes': typeof adminAdminTaxesRoute
  '/admin/transactions': typeof adminAdminTransactionsRoute
  '/admin/users': typeof adminAdminUsersRoute
  '/cart': typeof storeLayoutCartRoute
  '/checkout': typeof storeLayoutCheckoutRoute
  '/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/orders': typeof storeLayoutOrdersRoute
  '/profile': typeof storeLayoutProfileRoute
  '/track-order': typeof storeLayoutTrackOrderRoute
  '/wishlist': typeof storeLayoutWishlistRoute
  '/dashboard': typeof vendorLayoutDashboardRoute
  '/my-shop': typeof vendorLayoutMyShopRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/admin': typeof adminAdminIndexRoute
  '/': typeof storeLayoutIndexRoute
  '/admin/orders/$orderId': typeof adminAdminOrdersOrderIdRoute
  '/admin/tenants/$tenantId': typeof adminAdminTenantsTenantIdRoute
  '/category/$slug': typeof storeLayoutCategorySlugRoute
  '/product/$productId': typeof storeLayoutProductProductIdRoute
  '/store/$slug': typeof storeLayoutStoreSlugRoute
  '/shop/$slug/attributes': typeof vendorShopSlugAttributesRoute
  '/shop/$slug/brands': typeof vendorShopSlugBrandsRoute
  '/shop/$slug/categories': typeof vendorShopSlugCategoriesRoute
  '/shop/$slug/coupons': typeof vendorShopSlugCouponsRoute
  '/shop/$slug/reviews': typeof vendorShopSlugReviewsRoute
  '/shop/$slug/settings': typeof vendorShopSlugSettingsRoute
  '/shop/$slug/shipping': typeof vendorShopSlugShippingRoute
  '/shop/$slug/staff': typeof vendorShopSlugStaffRoute
  '/shop/$slug/tags': typeof vendorShopSlugTagsRoute
  '/shop/$slug/taxes': typeof vendorShopSlugTaxesRoute
  '/shop/$slug/transactions': typeof vendorShopSlugTransactionsRoute
  '/admin/orders': typeof adminAdminOrdersIndexRoute
  '/admin/tenants': typeof adminAdminTenantsIndexRoute
  '/category': typeof storeLayoutCategoryIndexRoute
  '/product': typeof storeLayoutProductIndexRoute
  '/store': typeof storeLayoutStoreIndexRoute
  '/shop/$slug': typeof vendorShopSlugIndexRoute
  '/shop/$slug/orders/$orderId': typeof vendorShopSlugOrdersOrderIdRoute
  '/shop/$slug/orders': typeof vendorShopSlugOrdersIndexRoute
  '/shop/$slug/products': typeof vendorShopSlugProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)/admin': typeof adminAdminRouteWithChildren
  '/(admin)/forbidden': typeof adminForbiddenRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/vendor-sign-up': typeof authVendorSignUpRoute
  '/(store)/_layout': typeof storeLayoutRouteWithChildren
  '/(vendor)/_layout': typeof vendorLayoutRouteWithChildren
  '/(admin)/admin/attributes': typeof adminAdminAttributesRoute
  '/(admin)/admin/brands': typeof adminAdminBrandsRoute
  '/(admin)/admin/categories': typeof adminAdminCategoriesRoute
  '/(admin)/admin/coupons': typeof adminAdminCouponsRoute
  '/(admin)/admin/my-store': typeof adminAdminMyStoreRoute
  '/(admin)/admin/products': typeof adminAdminProductsRoute
  '/(admin)/admin/reviews': typeof adminAdminReviewsRoute
  '/(admin)/admin/settings': typeof adminAdminSettingsRoute
  '/(admin)/admin/staff': typeof adminAdminStaffRoute
  '/(admin)/admin/tags': typeof adminAdminTagsRoute
  '/(admin)/admin/taxes': typeof adminAdminTaxesRoute
  '/(admin)/admin/transactions': typeof adminAdminTransactionsRoute
  '/(admin)/admin/users': typeof adminAdminUsersRoute
  '/(store)/_layout/cart': typeof storeLayoutCartRoute
  '/(store)/_layout/checkout': typeof storeLayoutCheckoutRoute
  '/(store)/_layout/order-confirmation': typeof storeLayoutOrderConfirmationRoute
  '/(store)/_layout/orders': typeof storeLayoutOrdersRoute
  '/(store)/_layout/profile': typeof storeLayoutProfileRoute
  '/(store)/_layout/track-order': typeof storeLayoutTrackOrderRoute
  '/(store)/_layout/wishlist': typeof storeLayoutWishlistRoute
  '/(vendor)/_layout/dashboard': typeof vendorLayoutDashboardRoute
  '/(vendor)/_layout/my-shop': typeof vendorLayoutMyShopRoute
  '/(vendor)/shop/$slug': typeof vendorShopSlugRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(store)/_layout/': typeof storeLayoutIndexRoute
  '/(admin)/admin/orders/$orderId': typeof adminAdminOrdersOrderIdRoute
  '/(admin)/admin/tenants/$tenantId': typeof adminAdminTenantsTenantIdRoute
  '/(store)/_layout/category/$slug': typeof storeLayoutCategorySlugRoute
  '/(store)/_layout/product/$productId': typeof storeLayoutProductProductIdRoute
  '/(store)/_layout/store/$slug': typeof storeLayoutStoreSlugRoute
  '/(vendor)/shop/$slug/attributes': typeof vendorShopSlugAttributesRoute
  '/(vendor)/shop/$slug/brands': typeof vendorShopSlugBrandsRoute
  '/(vendor)/shop/$slug/categories': typeof vendorShopSlugCategoriesRoute
  '/(vendor)/shop/$slug/coupons': typeof vendorShopSlugCouponsRoute
  '/(vendor)/shop/$slug/reviews': typeof vendorShopSlugReviewsRoute
  '/(vendor)/shop/$slug/settings': typeof vendorShopSlugSettingsRoute
  '/(vendor)/shop/$slug/shipping': typeof vendorShopSlugShippingRoute
  '/(vendor)/shop/$slug/staff': typeof vendorShopSlugStaffRoute
  '/(vendor)/shop/$slug/tags': typeof vendorShopSlugTagsRoute
  '/(vendor)/shop/$slug/taxes': typeof vendorShopSlugTaxesRoute
  '/(vendor)/shop/$slug/transactions': typeof vendorShopSlugTransactionsRoute
  '/(admin)/admin/orders/': typeof adminAdminOrdersIndexRoute
  '/(admin)/admin/tenants/': typeof adminAdminTenantsIndexRoute
  '/(store)/_layout/category/': typeof storeLayoutCategoryIndexRoute
  '/(store)/_layout/product/': typeof storeLayoutProductIndexRoute
  '/(store)/_layout/store/': typeof storeLayoutStoreIndexRoute
  '/(vendor)/shop/$slug/': typeof vendorShopSlugIndexRoute
  '/(vendor)/shop/$slug/orders/$orderId': typeof vendorShopSlugOrdersOrderIdRoute
  '/(vendor)/shop/$slug/orders/': typeof vendorShopSlugOrdersIndexRoute
  '/(vendor)/shop/$slug/products/': typeof vendorShopSlugProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/forbidden'
    | '/sign-in'
    | '/sign-up'
    | '/vendor-sign-up'
    | '/admin/attributes'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/my-store'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tags'
    | '/admin/taxes'
    | '/admin/transactions'
    | '/admin/users'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/orders'
    | '/profile'
    | '/track-order'
    | '/wishlist'
    | '/dashboard'
    | '/my-shop'
    | '/shop/$slug'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/admin/'
    | '/'
    | '/admin/orders/$orderId'
    | '/admin/tenants/$tenantId'
    | '/category/$slug'
    | '/product/$productId'
    | '/store/$slug'
    | '/shop/$slug/attributes'
    | '/shop/$slug/brands'
    | '/shop/$slug/categories'
    | '/shop/$slug/coupons'
    | '/shop/$slug/reviews'
    | '/shop/$slug/settings'
    | '/shop/$slug/shipping'
    | '/shop/$slug/staff'
    | '/shop/$slug/tags'
    | '/shop/$slug/taxes'
    | '/shop/$slug/transactions'
    | '/admin/orders/'
    | '/admin/tenants/'
    | '/category/'
    | '/product/'
    | '/store/'
    | '/shop/$slug/'
    | '/shop/$slug/orders/$orderId'
    | '/shop/$slug/orders/'
    | '/shop/$slug/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/sign-in'
    | '/sign-up'
    | '/vendor-sign-up'
    | '/admin/attributes'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/my-store'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tags'
    | '/admin/taxes'
    | '/admin/transactions'
    | '/admin/users'
    | '/cart'
    | '/checkout'
    | '/order-confirmation'
    | '/orders'
    | '/profile'
    | '/track-order'
    | '/wishlist'
    | '/dashboard'
    | '/my-shop'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/admin'
    | '/'
    | '/admin/orders/$orderId'
    | '/admin/tenants/$tenantId'
    | '/category/$slug'
    | '/product/$productId'
    | '/store/$slug'
    | '/shop/$slug/attributes'
    | '/shop/$slug/brands'
    | '/shop/$slug/categories'
    | '/shop/$slug/coupons'
    | '/shop/$slug/reviews'
    | '/shop/$slug/settings'
    | '/shop/$slug/shipping'
    | '/shop/$slug/staff'
    | '/shop/$slug/tags'
    | '/shop/$slug/taxes'
    | '/shop/$slug/transactions'
    | '/admin/orders'
    | '/admin/tenants'
    | '/category'
    | '/product'
    | '/store'
    | '/shop/$slug'
    | '/shop/$slug/orders/$orderId'
    | '/shop/$slug/orders'
    | '/shop/$slug/products'
  id:
    | '__root__'
    | '/(admin)/admin'
    | '/(admin)/forbidden'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/vendor-sign-up'
    | '/(store)/_layout'
    | '/(vendor)/_layout'
    | '/(admin)/admin/attributes'
    | '/(admin)/admin/brands'
    | '/(admin)/admin/categories'
    | '/(admin)/admin/coupons'
    | '/(admin)/admin/my-store'
    | '/(admin)/admin/products'
    | '/(admin)/admin/reviews'
    | '/(admin)/admin/settings'
    | '/(admin)/admin/staff'
    | '/(admin)/admin/tags'
    | '/(admin)/admin/taxes'
    | '/(admin)/admin/transactions'
    | '/(admin)/admin/users'
    | '/(store)/_layout/cart'
    | '/(store)/_layout/checkout'
    | '/(store)/_layout/order-confirmation'
    | '/(store)/_layout/orders'
    | '/(store)/_layout/profile'
    | '/(store)/_layout/track-order'
    | '/(store)/_layout/wishlist'
    | '/(vendor)/_layout/dashboard'
    | '/(vendor)/_layout/my-shop'
    | '/(vendor)/shop/$slug'
    | '/api/auth/$'
    | '/api/webhooks/stripe'
    | '/(admin)/admin/'
    | '/(store)/_layout/'
    | '/(admin)/admin/orders/$orderId'
    | '/(admin)/admin/tenants/$tenantId'
    | '/(store)/_layout/category/$slug'
    | '/(store)/_layout/product/$productId'
    | '/(store)/_layout/store/$slug'
    | '/(vendor)/shop/$slug/attributes'
    | '/(vendor)/shop/$slug/brands'
    | '/(vendor)/shop/$slug/categories'
    | '/(vendor)/shop/$slug/coupons'
    | '/(vendor)/shop/$slug/reviews'
    | '/(vendor)/shop/$slug/settings'
    | '/(vendor)/shop/$slug/shipping'
    | '/(vendor)/shop/$slug/staff'
    | '/(vendor)/shop/$slug/tags'
    | '/(vendor)/shop/$slug/taxes'
    | '/(vendor)/shop/$slug/transactions'
    | '/(admin)/admin/orders/'
    | '/(admin)/admin/tenants/'
    | '/(store)/_layout/category/'
    | '/(store)/_layout/product/'
    | '/(store)/_layout/store/'
    | '/(vendor)/shop/$slug/'
    | '/(vendor)/shop/$slug/orders/$orderId'
    | '/(vendor)/shop/$slug/orders/'
    | '/(vendor)/shop/$slug/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminAdminRoute: typeof adminAdminRouteWithChildren
  adminForbiddenRoute: typeof adminForbiddenRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVendorSignUpRoute: typeof authVendorSignUpRoute
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  vendorLayoutRoute: typeof vendorLayoutRouteWithChildren
  vendorShopSlugRoute: typeof vendorShopSlugRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(vendor)/_layout': {
      id: '/(vendor)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vendorLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout': {
      id: '/(store)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/vendor-sign-up': {
      id: '/(auth)/vendor-sign-up'
      path: '/vendor-sign-up'
      fullPath: '/vendor-sign-up'
      preLoaderRoute: typeof authVendorSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/forbidden': {
      id: '/(admin)/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof adminForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/': {
      id: '/(store)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeLayoutIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vendor)/shop/$slug': {
      id: '/(vendor)/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof vendorShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(vendor)/_layout/my-shop': {
      id: '/(vendor)/_layout/my-shop'
      path: '/my-shop'
      fullPath: '/my-shop'
      preLoaderRoute: typeof vendorLayoutMyShopRouteImport
      parentRoute: typeof vendorLayoutRoute
    }
    '/(vendor)/_layout/dashboard': {
      id: '/(vendor)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof vendorLayoutDashboardRouteImport
      parentRoute: typeof vendorLayoutRoute
    }
    '/(store)/_layout/wishlist': {
      id: '/(store)/_layout/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof storeLayoutWishlistRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/track-order': {
      id: '/(store)/_layout/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof storeLayoutTrackOrderRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/profile': {
      id: '/(store)/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof storeLayoutProfileRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/orders': {
      id: '/(store)/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof storeLayoutOrdersRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/order-confirmation': {
      id: '/(store)/_layout/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof storeLayoutOrderConfirmationRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/checkout': {
      id: '/(store)/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof storeLayoutCheckoutRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/cart': {
      id: '/(store)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeLayoutCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(admin)/admin/users': {
      id: '/(admin)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminAdminUsersRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/transactions': {
      id: '/(admin)/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof adminAdminTransactionsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/taxes': {
      id: '/(admin)/admin/taxes'
      path: '/taxes'
      fullPath: '/admin/taxes'
      preLoaderRoute: typeof adminAdminTaxesRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/tags': {
      id: '/(admin)/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof adminAdminTagsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/staff': {
      id: '/(admin)/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof adminAdminStaffRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/settings': {
      id: '/(admin)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof adminAdminSettingsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/reviews': {
      id: '/(admin)/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof adminAdminReviewsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/products': {
      id: '/(admin)/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof adminAdminProductsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/my-store': {
      id: '/(admin)/admin/my-store'
      path: '/my-store'
      fullPath: '/admin/my-store'
      preLoaderRoute: typeof adminAdminMyStoreRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/coupons': {
      id: '/(admin)/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof adminAdminCouponsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/categories': {
      id: '/(admin)/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof adminAdminCategoriesRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/brands': {
      id: '/(admin)/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof adminAdminBrandsRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/attributes': {
      id: '/(admin)/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof adminAdminAttributesRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(vendor)/shop/$slug/': {
      id: '/(vendor)/shop/$slug/'
      path: '/'
      fullPath: '/shop/$slug/'
      preLoaderRoute: typeof vendorShopSlugIndexRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(store)/_layout/store/': {
      id: '/(store)/_layout/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof storeLayoutStoreIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/': {
      id: '/(store)/_layout/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof storeLayoutProductIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/category/': {
      id: '/(store)/_layout/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof storeLayoutCategoryIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(admin)/admin/tenants/': {
      id: '/(admin)/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof adminAdminTenantsIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/orders/': {
      id: '/(admin)/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof adminAdminOrdersIndexRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(vendor)/shop/$slug/transactions': {
      id: '/(vendor)/shop/$slug/transactions'
      path: '/transactions'
      fullPath: '/shop/$slug/transactions'
      preLoaderRoute: typeof vendorShopSlugTransactionsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/taxes': {
      id: '/(vendor)/shop/$slug/taxes'
      path: '/taxes'
      fullPath: '/shop/$slug/taxes'
      preLoaderRoute: typeof vendorShopSlugTaxesRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/tags': {
      id: '/(vendor)/shop/$slug/tags'
      path: '/tags'
      fullPath: '/shop/$slug/tags'
      preLoaderRoute: typeof vendorShopSlugTagsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/staff': {
      id: '/(vendor)/shop/$slug/staff'
      path: '/staff'
      fullPath: '/shop/$slug/staff'
      preLoaderRoute: typeof vendorShopSlugStaffRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/shipping': {
      id: '/(vendor)/shop/$slug/shipping'
      path: '/shipping'
      fullPath: '/shop/$slug/shipping'
      preLoaderRoute: typeof vendorShopSlugShippingRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/settings': {
      id: '/(vendor)/shop/$slug/settings'
      path: '/settings'
      fullPath: '/shop/$slug/settings'
      preLoaderRoute: typeof vendorShopSlugSettingsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/reviews': {
      id: '/(vendor)/shop/$slug/reviews'
      path: '/reviews'
      fullPath: '/shop/$slug/reviews'
      preLoaderRoute: typeof vendorShopSlugReviewsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/coupons': {
      id: '/(vendor)/shop/$slug/coupons'
      path: '/coupons'
      fullPath: '/shop/$slug/coupons'
      preLoaderRoute: typeof vendorShopSlugCouponsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/categories': {
      id: '/(vendor)/shop/$slug/categories'
      path: '/categories'
      fullPath: '/shop/$slug/categories'
      preLoaderRoute: typeof vendorShopSlugCategoriesRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/brands': {
      id: '/(vendor)/shop/$slug/brands'
      path: '/brands'
      fullPath: '/shop/$slug/brands'
      preLoaderRoute: typeof vendorShopSlugBrandsRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/attributes': {
      id: '/(vendor)/shop/$slug/attributes'
      path: '/attributes'
      fullPath: '/shop/$slug/attributes'
      preLoaderRoute: typeof vendorShopSlugAttributesRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(store)/_layout/store/$slug': {
      id: '/(store)/_layout/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof storeLayoutStoreSlugRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/product/$productId': {
      id: '/(store)/_layout/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof storeLayoutProductProductIdRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/category/$slug': {
      id: '/(store)/_layout/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof storeLayoutCategorySlugRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(admin)/admin/tenants/$tenantId': {
      id: '/(admin)/admin/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof adminAdminTenantsTenantIdRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(admin)/admin/orders/$orderId': {
      id: '/(admin)/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof adminAdminOrdersOrderIdRouteImport
      parentRoute: typeof adminAdminRoute
    }
    '/(vendor)/shop/$slug/products/': {
      id: '/(vendor)/shop/$slug/products/'
      path: '/products'
      fullPath: '/shop/$slug/products/'
      preLoaderRoute: typeof vendorShopSlugProductsIndexRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/orders/': {
      id: '/(vendor)/shop/$slug/orders/'
      path: '/orders'
      fullPath: '/shop/$slug/orders/'
      preLoaderRoute: typeof vendorShopSlugOrdersIndexRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
    '/(vendor)/shop/$slug/orders/$orderId': {
      id: '/(vendor)/shop/$slug/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/shop/$slug/orders/$orderId'
      preLoaderRoute: typeof vendorShopSlugOrdersOrderIdRouteImport
      parentRoute: typeof vendorShopSlugRoute
    }
  }
}

interface adminAdminRouteChildren {
  adminAdminAttributesRoute: typeof adminAdminAttributesRoute
  adminAdminBrandsRoute: typeof adminAdminBrandsRoute
  adminAdminCategoriesRoute: typeof adminAdminCategoriesRoute
  adminAdminCouponsRoute: typeof adminAdminCouponsRoute
  adminAdminMyStoreRoute: typeof adminAdminMyStoreRoute
  adminAdminProductsRoute: typeof adminAdminProductsRoute
  adminAdminReviewsRoute: typeof adminAdminReviewsRoute
  adminAdminSettingsRoute: typeof adminAdminSettingsRoute
  adminAdminStaffRoute: typeof adminAdminStaffRoute
  adminAdminTagsRoute: typeof adminAdminTagsRoute
  adminAdminTaxesRoute: typeof adminAdminTaxesRoute
  adminAdminTransactionsRoute: typeof adminAdminTransactionsRoute
  adminAdminUsersRoute: typeof adminAdminUsersRoute
  adminAdminIndexRoute: typeof adminAdminIndexRoute
  adminAdminOrdersOrderIdRoute: typeof adminAdminOrdersOrderIdRoute
  adminAdminTenantsTenantIdRoute: typeof adminAdminTenantsTenantIdRoute
  adminAdminOrdersIndexRoute: typeof adminAdminOrdersIndexRoute
  adminAdminTenantsIndexRoute: typeof adminAdminTenantsIndexRoute
}

const adminAdminRouteChildren: adminAdminRouteChildren = {
  adminAdminAttributesRoute: adminAdminAttributesRoute,
  adminAdminBrandsRoute: adminAdminBrandsRoute,
  adminAdminCategoriesRoute: adminAdminCategoriesRoute,
  adminAdminCouponsRoute: adminAdminCouponsRoute,
  adminAdminMyStoreRoute: adminAdminMyStoreRoute,
  adminAdminProductsRoute: adminAdminProductsRoute,
  adminAdminReviewsRoute: adminAdminReviewsRoute,
  adminAdminSettingsRoute: adminAdminSettingsRoute,
  adminAdminStaffRoute: adminAdminStaffRoute,
  adminAdminTagsRoute: adminAdminTagsRoute,
  adminAdminTaxesRoute: adminAdminTaxesRoute,
  adminAdminTransactionsRoute: adminAdminTransactionsRoute,
  adminAdminUsersRoute: adminAdminUsersRoute,
  adminAdminIndexRoute: adminAdminIndexRoute,
  adminAdminOrdersOrderIdRoute: adminAdminOrdersOrderIdRoute,
  adminAdminTenantsTenantIdRoute: adminAdminTenantsTenantIdRoute,
  adminAdminOrdersIndexRoute: adminAdminOrdersIndexRoute,
  adminAdminTenantsIndexRoute: adminAdminTenantsIndexRoute,
}

const adminAdminRouteWithChildren = adminAdminRoute._addFileChildren(
  adminAdminRouteChildren,
)

interface storeLayoutRouteChildren {
  storeLayoutCartRoute: typeof storeLayoutCartRoute
  storeLayoutCheckoutRoute: typeof storeLayoutCheckoutRoute
  storeLayoutOrderConfirmationRoute: typeof storeLayoutOrderConfirmationRoute
  storeLayoutOrdersRoute: typeof storeLayoutOrdersRoute
  storeLayoutProfileRoute: typeof storeLayoutProfileRoute
  storeLayoutTrackOrderRoute: typeof storeLayoutTrackOrderRoute
  storeLayoutWishlistRoute: typeof storeLayoutWishlistRoute
  storeLayoutIndexRoute: typeof storeLayoutIndexRoute
  storeLayoutCategorySlugRoute: typeof storeLayoutCategorySlugRoute
  storeLayoutProductProductIdRoute: typeof storeLayoutProductProductIdRoute
  storeLayoutStoreSlugRoute: typeof storeLayoutStoreSlugRoute
  storeLayoutCategoryIndexRoute: typeof storeLayoutCategoryIndexRoute
  storeLayoutProductIndexRoute: typeof storeLayoutProductIndexRoute
  storeLayoutStoreIndexRoute: typeof storeLayoutStoreIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeLayoutCartRoute: storeLayoutCartRoute,
  storeLayoutCheckoutRoute: storeLayoutCheckoutRoute,
  storeLayoutOrderConfirmationRoute: storeLayoutOrderConfirmationRoute,
  storeLayoutOrdersRoute: storeLayoutOrdersRoute,
  storeLayoutProfileRoute: storeLayoutProfileRoute,
  storeLayoutTrackOrderRoute: storeLayoutTrackOrderRoute,
  storeLayoutWishlistRoute: storeLayoutWishlistRoute,
  storeLayoutIndexRoute: storeLayoutIndexRoute,
  storeLayoutCategorySlugRoute: storeLayoutCategorySlugRoute,
  storeLayoutProductProductIdRoute: storeLayoutProductProductIdRoute,
  storeLayoutStoreSlugRoute: storeLayoutStoreSlugRoute,
  storeLayoutCategoryIndexRoute: storeLayoutCategoryIndexRoute,
  storeLayoutProductIndexRoute: storeLayoutProductIndexRoute,
  storeLayoutStoreIndexRoute: storeLayoutStoreIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

interface vendorLayoutRouteChildren {
  vendorLayoutDashboardRoute: typeof vendorLayoutDashboardRoute
  vendorLayoutMyShopRoute: typeof vendorLayoutMyShopRoute
}

const vendorLayoutRouteChildren: vendorLayoutRouteChildren = {
  vendorLayoutDashboardRoute: vendorLayoutDashboardRoute,
  vendorLayoutMyShopRoute: vendorLayoutMyShopRoute,
}

const vendorLayoutRouteWithChildren = vendorLayoutRoute._addFileChildren(
  vendorLayoutRouteChildren,
)

interface vendorShopSlugRouteChildren {
  vendorShopSlugAttributesRoute: typeof vendorShopSlugAttributesRoute
  vendorShopSlugBrandsRoute: typeof vendorShopSlugBrandsRoute
  vendorShopSlugCategoriesRoute: typeof vendorShopSlugCategoriesRoute
  vendorShopSlugCouponsRoute: typeof vendorShopSlugCouponsRoute
  vendorShopSlugReviewsRoute: typeof vendorShopSlugReviewsRoute
  vendorShopSlugSettingsRoute: typeof vendorShopSlugSettingsRoute
  vendorShopSlugShippingRoute: typeof vendorShopSlugShippingRoute
  vendorShopSlugStaffRoute: typeof vendorShopSlugStaffRoute
  vendorShopSlugTagsRoute: typeof vendorShopSlugTagsRoute
  vendorShopSlugTaxesRoute: typeof vendorShopSlugTaxesRoute
  vendorShopSlugTransactionsRoute: typeof vendorShopSlugTransactionsRoute
  vendorShopSlugIndexRoute: typeof vendorShopSlugIndexRoute
  vendorShopSlugOrdersOrderIdRoute: typeof vendorShopSlugOrdersOrderIdRoute
  vendorShopSlugOrdersIndexRoute: typeof vendorShopSlugOrdersIndexRoute
  vendorShopSlugProductsIndexRoute: typeof vendorShopSlugProductsIndexRoute
}

const vendorShopSlugRouteChildren: vendorShopSlugRouteChildren = {
  vendorShopSlugAttributesRoute: vendorShopSlugAttributesRoute,
  vendorShopSlugBrandsRoute: vendorShopSlugBrandsRoute,
  vendorShopSlugCategoriesRoute: vendorShopSlugCategoriesRoute,
  vendorShopSlugCouponsRoute: vendorShopSlugCouponsRoute,
  vendorShopSlugReviewsRoute: vendorShopSlugReviewsRoute,
  vendorShopSlugSettingsRoute: vendorShopSlugSettingsRoute,
  vendorShopSlugShippingRoute: vendorShopSlugShippingRoute,
  vendorShopSlugStaffRoute: vendorShopSlugStaffRoute,
  vendorShopSlugTagsRoute: vendorShopSlugTagsRoute,
  vendorShopSlugTaxesRoute: vendorShopSlugTaxesRoute,
  vendorShopSlugTransactionsRoute: vendorShopSlugTransactionsRoute,
  vendorShopSlugIndexRoute: vendorShopSlugIndexRoute,
  vendorShopSlugOrdersOrderIdRoute: vendorShopSlugOrdersOrderIdRoute,
  vendorShopSlugOrdersIndexRoute: vendorShopSlugOrdersIndexRoute,
  vendorShopSlugProductsIndexRoute: vendorShopSlugProductsIndexRoute,
}

const vendorShopSlugRouteWithChildren = vendorShopSlugRoute._addFileChildren(
  vendorShopSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminAdminRoute: adminAdminRouteWithChildren,
  adminForbiddenRoute: adminForbiddenRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVendorSignUpRoute: authVendorSignUpRoute,
  storeLayoutRoute: storeLayoutRouteWithChildren,
  vendorLayoutRoute: vendorLayoutRouteWithChildren,
  vendorShopSlugRoute: vendorShopSlugRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
